version: 2.1

jobs:
  build-and-test:
    working_directory: ~/firebase-firestore-rule-testing-demo
    docker:
      - image: cimg/node:15.3.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{.Environment.CACHE_VERSION}}-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm ci
            sudo npm i -g firebase-tools
      - save_cache:
          key: dependency-cache-{{.Environment.CACHE_VERSION}}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit tests
          command: npm run test
          when: always

workflows:
  tests:
    jobs:
      - build-and-test
