version: 2.1

orbs:
  node: circleci/node@3.0.0
jobs:
  prepare-dependencies:
    working_directory: ~/firebase-firestore-rule-testing-demo
    docker:
      - image: node:current
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm i -g firebase-tools
            npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - store_artifacts:
          path: package-lock.json
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit-tests:
    working_directory: ~/firebase-firestore-rule-testing-demo
    docker:
      - image: node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: npm run test
          when: always

workflows:
  tests:
    jobs:
      - prepare-dependencies
      - unit-tests:
          requires:
            - prepare-dependencies
